Repository hmcts/fact-frontend, pull requests merged in 2020-12, with the labels that each got.

#180 FACT-278: DAC - Remove alt text on image
  src/main/views/court-details/in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-180

#186 fixing test to get text for array of elements
  src/test/functional/steps/court-details.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-186

#188 FACT-71: Accessibility statement
  src/main/controllers/AccessibilityStatementController.ts
  src/main/locales/cy/accessibility-statement.json
  src/main/locales/en/accessibility-statement.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/accessibility-statement.njk
  src/main/views/acessibility-statement.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-188

#193 FACT-71: Remove 2 paragraphs
  src/main/locales/cy/accessibility-statement.json
  src/main/locales/en/accessibility-statement.json
  src/main/views/accessibility-statement.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-193

#185 FACT-279: DAC - Search results
  src/main/locales/cy/search/location.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-185

#199 FACT-251, FACT-253: Amend rule for displaying email address
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/Enquiries.ts
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-199

#172 Cookie banner
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/locales/cy/template.json
  src/main/locales/en/template.json
  src/main/modules/nunjucks/index.ts
  src/main/views/template.njk
  src/main/views/webpack/css.njk
  src/test/functional/features/cookie-banner.feature
  src/test/functional/steps/cookie-banner.ts
  src/test/functional/steps/homepage.ts
  src/test/functional/support/hooks.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-172

#202 FACT-267: singular/plural search results
  src/main/controllers/search/SearchResultsController.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/interfaces/PostcodeResultsData.ts
  src/main/interfaces/SearchResultsData.ts
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/search/location.json
  src/main/locales/en/postcode-results.json
  src/main/locales/en/search/location.json
  src/main/views/postcode-results.njk
  src/main/views/search/location.njk
  src/test/unit/test/controllers/search/SearchResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-202
