Repository hmcts/fact-frontend, pull requests merged in 2020-09, with the labels that each got.

#15 Add smoke test
  jest.smoke.config.js
  package.json
  src/test/smoke/smoke.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-15

#13 CTF-11: Add home page
  config/default.json
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/views/home.njk
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-13

#25 setting up cucumber js
  README.md
  cucumber.js
  package.json
  src/test/config.ts
  src/test/functional/features/homepage.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/homepage.ts
  src/test/functional/support/hooks.ts
  src/test/functional/support/scope.ts
  src/test/smoke/smoke.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-25

#26 CTF-30: Add i18n
  .gitignore
  config/default.json
  jest.coverage.config.js
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/locales/cy/error.json
  src/main/locales/cy/home.json
  src/main/locales/cy/notFound.json
  src/main/locales/cy/template.json
  src/main/locales/en/error.json
  src/main/locales/en/home.json
  src/main/locales/en/notFound.json
  src/main/locales/en/template.json
  src/main/modules/i18next/index.ts
  src/main/routes/home.ts
  src/main/views/error.njk
  src/main/views/home.njk
  src/main/views/not-found.njk
  src/main/views/template.njk
  src/test/unit/modules/i18next.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-26

#32 Ctf 38 court name known
  package.json
  src/main/controllers/home.ts
  src/main/controllers/search.ts
  src/main/locales/en/search/location.json
  src/main/locales/en/search/option.json
  src/main/routes/home.ts
  src/main/routes/search.ts
  src/main/server.ts
  src/main/views/home.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
  src/main/views/template.njk
  src/test/functional/features/search.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/homepage.ts
  src/test/functional/steps/search.ts
  src/test/functional/support/hooks.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/routes/search.ts
  src/test/unit/controllers/home.ts
  src/test/unit/controllers/search.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-32

#35 Ctf 35/add api to health check
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.preview.template.yaml
  charts/fact-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.json
  config/default.yaml
  config/dev.json
  config/dev.yaml
  config/production.json
  config/production.yaml
  config/test.json
  config/test.yaml
  renovate.json
  src/main/app.ts
  src/main/routes/health.ts
  src/main/utils/healthOptions.ts
  src/test/routes/health.ts
  src/test/routes/home.ts
  src/test/unit/utils/healthOptions.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-35

#33 Ctf 38 clean up
  .gitignore
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/views/search/location.njk
  src/main/views/search/option.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-33
