Repository hmcts/fact-frontend, pull requests merged in 2020-11, with the labels that each got.

#74 Fact 59 select area of law
  api/areasOfLaw.json
  api/childcareAndParentingAreaOfLaw.json
  api/fact-api-stubs.ts
  api/familyAreaOfLaw.json
  api/moneyAreaOfLaw.json
  src/main/controllers/ChooseActionController.ts
  src/main/controllers/CourtDetailsController.ts
  src/main/controllers/search/LocationSearchController.ts
  src/main/controllers/search/SearchOptionController.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/ServiceData.ts
  src/main/interfaces/ServicesData.ts
  src/main/locales/en/choose-service.json
  src/main/locales/en/service.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/utils/FactApi.ts
  src/main/views/choose-service.njk
  src/main/views/service.njk
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/features/no-name.feature
  src/test/functional/features/services.feature
  src/test/functional/steps/area-of-law/area-of-law.ts
  src/test/functional/steps/area-of-law/childcare-and-parenting-service-area.ts
  src/test/functional/steps/area-of-law/crime-service-area.ts
  src/test/functional/steps/area-of-law/family-service-area.ts
  src/test/functional/steps/area-of-law/harm-and-abuse-service-area.ts
  src/test/functional/steps/area-of-law/money-service-area.ts
  src/test/functional/steps/no-name.ts
  src/test/resources/childcare-and-parenting-area-of-law-results.json
  src/test/resources/family-area-of-law-results.json
  src/test/resources/money-service-results.json
  src/test/resources/service-results.json
  src/test/unit/test/controllers/ChooseActionController.ts
  src/test/unit/test/controllers/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/ChooseServiceController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-74

#81 FACT_109:Court Name Not Known: Select and view other options
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/controllers/service/UnknownServiceController.ts
  src/main/locales/cy/choose-service.json
  src/main/locales/cy/court-details.json
  src/main/locales/cy/service.json
  src/main/locales/cy/unknownService.json
  src/main/locales/en/unknownService.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/unknown-service.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/unknown-service.feature
  src/test/functional/steps/unknown-service.ts
  src/test/unit/test/controllers/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/UnknownServiceController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-81

#84 Fact 59 renaming
  api/fact-api-stubs.ts
  api/services.json
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-84

#85 Add pa11y tests and test coverage
  src/main/controllers/CourtDetailsController.ts
  src/main/utils/CourtDetailsUtils.ts
  src/main/views/choose-service.njk
  src/main/views/service.njk
  src/test/a11y/a11y.ts
  src/test/unit/test/controllers/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/ChooseServiceController.ts
  src/test/unit/test/controllers/CourtDetailsController.ts
  src/test/unit/test/utils/CourtDetailsUtils.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-85

#86 Fact 59 use service slug
  charts/fact-frontend/Chart.yaml
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/ServiceAreasData.ts
  src/main/interfaces/ServicesData.ts
  src/main/utils/FactApi.ts
  src/main/views/choose-service.njk
  src/main/views/service.njk
  src/test/a11y/a11y.ts
  src/test/unit/test/controllers/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/ChooseServiceController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-86

#90 Add preview API
  src/main/views/search/location.njk
  src/test/functional/features/court-details.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-90

#92 Autoscaling Update values.yaml
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-92

#95 Add text
  src/main/app.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/locales/cy/search/location.json
  src/main/locales/en/search/location.json
  src/main/views/search/location.njk
  src/test/functional/features/search.feature
  src/test/functional/steps/search.ts
  src/test/unit/test/controllers/search/SearchResultsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-95

#99 Redirects
  src/main/controllers/search/LocationSearchController.ts
  src/main/controllers/search/SearchOptionController.ts
  src/main/routes.ts
  src/main/views/search/location.njk
  src/test/a11y/a11y.ts
  src/test/unit/test/controllers/search/LocationSearchController.ts
  src/test/unit/test/controllers/search/SearchOptionController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-99

#98 FACT-183: add Accept-Language header to api call
  src/main/controllers/CourtDetailsController.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/modules/i18next/index.ts
  src/main/utils/FactApi.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-98

#101 nodejs update for HPA Update Chart.yaml
  charts/fact-frontend/Chart.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-101

#102 FACT-182: welsh
  src/main/locales/cy/choose-action.json
  src/main/locales/cy/choose-service.json
  src/main/locales/cy/court-details.json
  src/main/locales/cy/error.json
  src/main/locales/cy/home.json
  src/main/locales/cy/notFound.json
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/locales/cy/service.json
  src/main/locales/cy/template.json
  src/main/locales/cy/unknownService.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-102

#97 Fact 81 view category result
  api/fact-api-stubs.ts
  api/money-claims-data.json
  api/money-service-data.json
  api/moneyAreaOfLaw.json
  api/services.json
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
  src/main/controllers/ChooseActionController.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/controllers/service/ServiceSearchResultsController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/ServiceAreasData.ts
  src/main/interfaces/ServiceSearchResults.ts
  src/main/locales/cy/service-results.json
  src/main/locales/en/service-results.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/utils/Action.ts
  src/main/utils/Catchment.ts
  src/main/utils/FactApi.ts
  src/main/views/choose-action.njk
  src/main/views/service-results.njk
  src/main/views/service.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/features/services.feature
  src/test/functional/features/view-money-claims-result.feature
  src/test/functional/steps/area-of-law/childcare-and-parenting-service-area.ts
  src/test/functional/steps/area-of-law/family-service-area.ts
  src/test/functional/steps/view-money-claims-result.ts
  src/test/unit/test/controllers/ChooseActionController.ts
  src/test/unit/test/controllers/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/ChooseServiceController.ts
  src/test/unit/test/controllers/ServiceSearchResultsController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-97

#103 Update values.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-103

#108 update redirects to include mapping between aol and service area
  src/main/routes.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-108

#110 FACT-182: Add welsh contact numbers
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/Enquiries.ts
  src/main/locales/cy/court-details.json
  src/main/locales/cy/template.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-110

#112 Fact 96 postcode search
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/PostcodeSearchData.ts
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/utils/validation.ts
  src/main/views/postcode-search.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/postcode-search.feature
  src/test/functional/steps/postcode-search.ts
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/service/ChooseServiceController.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
  src/test/unit/test/utils/validation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-112

#111 Fact 142 immigration service result
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/interfaces/ServiceAreasData.ts
  src/main/views/service-results.njk
  src/test/functional/features/view-immigration-result.feature
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-111

#114 Add serviceareas text
  src/main/controllers/service/ServiceSearchResultsController.ts
  src/main/interfaces/ServiceAreasData.ts
  src/main/interfaces/ServiceSearchResults.ts
  src/main/locales/cy/service-results.json
  src/main/locales/en/service-results.json
  src/main/views/service-results.njk
  src/test/unit/test/controllers/ServiceSearchResultsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-114

#117 Merge two strings into one
  src/main/controllers/service/ServiceSearchResultsController.ts
  src/main/interfaces/ServiceSearchResults.ts
  src/main/locales/cy/service-results.json
  src/main/locales/en/service-results.json
  src/main/views/service-results.njk
  src/test/unit/test/controllers/ServiceSearchResultsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-117

#116 Fact 137 postcode results
  api/court-details.json
  api/fact-api-stubs.ts
  api/service-areas.json
  api/utils.ts
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/PostcodeResultsQuery.ts
  src/main/interfaces/PostcodeSearchData.ts
  src/main/interfaces/ServiceAreasData.ts
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-results.json
  src/main/locales/en/postcode-search.json
  src/main/utils/Action.ts
  src/main/utils/FactApi.ts
  src/main/views/postcode-results.njk
  src/main/views/postcode-search.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/postcode-results.feature
  src/test/functional/steps/postcode-results.ts
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-116

#119 Fix accessibility error
  package.json
  src/main/views/choose-service.njk
  src/main/views/service.njk
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-119

#120 implement the matrix of doom
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ServiceAreaRedirect.ts
  src/main/modules/awilix/index.ts
  src/main/utils/Catchment.ts
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
  src/test/unit/test/controllers/service/ServiceAreaRedirect.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-120

#121 update redirects
  src/main/routes.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-121

#123 Fix pa11y timeout
  jest.a11y.config.js
  jest.timeout.config.js
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-123

#124 Add tag manager
  src/main/modules/helmet/index.ts
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-124

#125 using new endpoint
  src/main/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-125

#126 Update CPU request, add memory limit, bump chart
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-126

#128 Fact 186+199 beta banner and content info
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/views/template.njk
  src/test/functional/features/help-and-navigation.feature
  src/test/functional/steps/help-and-navigation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-128

#132 Fact 137 api clean up
  src/main/controllers/service/ServiceAreaRedirect.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/interfaces/PostcodeResultsQuery.ts
  src/main/interfaces/PostcodeSearchData.ts
  src/main/locales/cy/postcode-results.json
  src/main/locales/en/postcode-results.json
  src/main/routes.ts
  src/main/utils/FactApi.ts
  src/main/views/postcode-search.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/postcode-search.feature
  src/test/unit/test/controllers/service/ServiceAreaRedirect.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-132

#134 Update CPU request250, bump chart
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-134

#135 remove safe
  src/main/views/choose-action.njk
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/postcode-search.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-135

#137 Update CPU request100, bump chart
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-137

#136 Postcode results clean up
  api/fact-api-stubs.ts
  api/service-areas.json
  src/main/assets/scss/main.scss
  src/main/assets/scss/postcode-results.scss
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/PostcodeResultsData.ts
  src/main/interfaces/PostcodeSearchData.ts
  src/main/locales/cy/postcode-results.json
  src/main/locales/en/postcode-results.json
  src/main/utils/FactApi.ts
  src/main/views/postcode-results.njk
  src/main/views/webpack/css.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/postcode-results.feature
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-136

#141 Fix not find radio option
  src/main/controllers/service/ChooseServiceController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-141

#146 FACT-199: Refactor to use json language files
  src/main/locales/cy/template.json
  src/main/locales/en/template.json
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-146

#140 Fact 180 back link
  src/main/locales/cy/template.json
  src/main/locales/en/template.json
  src/main/views/choose-action.njk
  src/main/views/choose-service.njk
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/home.njk
  src/main/views/postcode-results.njk
  src/main/views/postcode-search.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
  src/main/views/service-results.njk
  src/main/views/service.njk
  src/main/views/template.njk
  src/test/functional/features/help-and-navigation.feature
  src/test/functional/steps/help-and-navigation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-140

#149 Fix service name in template
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/interfaces/PostcodeResultsData.ts
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-149

#150 Add quotes to html
  src/main/views/choose-service.njk
  src/main/views/service.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-150

#142 fact 217 - removing example for postcode
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/main/views/postcode-search.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-142

#151 displaying distance to 1 decimal place
  src/main/views/postcode-results.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-151

#152 Fact 224 prod data
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
  src/test/functional/features/court-details.feature
  src/test/functional/features/postcode-results.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-152

#155 FACT-182: welsh
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/cy/search/location.json
  src/main/locales/cy/template.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-155

#156 Update Env, bump chart
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-156

#157 FACT-182: welsh
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/postcode-search.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-157

#158 Fact 236 condition for image
  config/custom-environment-variables.yaml
  src/main/controllers/CourtDetailsController.ts
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/test/resources/court-details-results.json
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-158

#148 Fact 202 postcode error msg
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/main/utils/validation.ts
  src/test/functional/features/postcode-search.feature
  src/test/functional/steps/postcode-search.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
  src/test/unit/test/utils/validation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-148

#113 Add pa11y tests
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-113

#160 Removed unused imports
  src/main/views/choose-action.njk
  src/main/views/choose-service.njk
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/postcode-results.njk
  src/main/views/postcode-search.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
  src/main/views/service-results.njk
  src/main/views/service.njk
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-160

#162 FACT-241: scale images
  src/main/assets/scss/court-details.scss
  src/main/views/webpack/css.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-162

#163 FACT- 242 Remove field is blank from error message
  src/main/locales/cy/search/option.json
  src/main/locales/en/search/option.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-163

#164 Fact 238 childcare hint
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/main/views/postcode-search.njk
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-164

#168 Fix choose action page error message
  src/main/locales/cy/choose-action.json
  src/main/locales/en/choose-action.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-168

#165 FACT-239: chnage "Additional information" to covid message
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-165

#166 fact 248 - heading change
  src/main/locales/en/unknownService.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-166

#167 Fact 185 feedback link
  src/main/locales/cy/template.json
  src/main/locales/en/template.json
  src/main/utils/FactApi.ts
  src/test/functional/features/help-and-navigation.feature
  src/test/functional/steps/help-and-navigation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-167

#171 fix welsh change
  src/main/locales/cy/unknownService.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-171

#170 fact 247 - changing url to service-not-found
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/controllers/service/ChooseServiceController.ts
  src/main/locales/en/unknownService.json
  src/main/routes.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/unknown-service.feature
  src/test/functional/steps/unknown-service.ts
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-170

#161 fact 243 - change error message
  src/main/locales/cy/choose-service.json
  src/main/locales/cy/court-details.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/choose-service.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-161

#159 Fact 220 service area mapping
  api/court-details.json
  src/main/interfaces/CourtDetailsData.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-159

#174 changing tag to div to allow child tags
  src/main/views/court-details/in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-174

#178 Remove hyphens before displaying service area
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-178

#176 fact 249 - updating building facility info
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-176

#179 Update cucumber steps for new facility order
  src/main/views/acessibility-statement.njk
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-179

#177 FACT-261: Remove "Field is blank" from error messages.
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/test/functional/features/postcode-search.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-177

#175 FACT-250: Amend areas of law heading
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-175

#181 FACT-279: DAC - search results
  src/main/locales/cy/search/location.json
  src/main/locales/en/search/location.json
  src/main/views/search/location.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-181

#182 FACT-280: DAC - search results role="status"
  src/main/views/search/location.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-182

#183 FACT-281: DAC - Error title
  src/main/locales/cy/choose-action.json
  src/main/locales/cy/choose-service.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/locales/cy/service.json
  src/main/locales/en/choose-action.json
  src/main/locales/en/choose-service.json
  src/main/locales/en/postcode-search.json
  src/main/locales/en/search/location.json
  src/main/locales/en/search/option.json
  src/main/locales/en/service.json
  src/main/views/choose-action.njk
  src/main/views/choose-service.njk
  src/main/views/postcode-results.njk
  src/main/views/postcode-search.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
  src/main/views/service-results.njk
  src/main/views/service.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-183
