Repository hmcts/fact-frontend, pull requests merged in 2020-10, with the labels that each got.

#40 Ctf 41 view search results
  .eslintrc.js
  api/courts.json
  api/fact-api-stubs.ts
  jest.config.js
  jest.coverage.config.js
  jest.routes.config.js
  package.json
  src/main/app.ts
  src/main/container.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/home.ts
  src/main/controllers/search.ts
  src/main/controllers/search/LocationSearchController.ts
  src/main/controllers/search/SearchOptionController.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/interfaces/FactRequest.ts
  src/main/interfaces/HttpError.ts
  src/main/interfaces/Logger.ts
  src/main/interfaces/PageData.ts
  src/main/interfaces/SearchResultsData.ts
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/locales/en/search/location.json
  src/main/locales/en/search/option.json
  src/main/routes.ts
  src/main/routes/health.ts
  src/main/routes/home.ts
  src/main/routes/info.ts
  src/main/routes/search.ts
  src/main/utils/FactApi.ts
  src/main/utils/validation.ts
  src/main/views/macros/error-summary.njk
  src/main/views/search/location.njk
  src/main/views/search/option.njk
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  src/test/config.ts
  src/test/functional/features/search.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/search.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/routes/health.ts
  src/test/routes/home.ts
  src/test/routes/search.ts
  src/test/unit/controllers/home.ts
  src/test/unit/controllers/search.ts
  src/test/unit/sample.ts
  src/test/unit/test/controllers/HomeController.ts
  src/test/unit/test/controllers/search/LocationSearchController.ts
  src/test/unit/test/controllers/search/SearchOptionController.ts
  src/test/unit/test/controllers/search/SearchResultsController.ts
  src/test/unit/test/modules/i18next.ts
  src/test/unit/test/utils/FactApi.ts
  src/test/unit/test/utils/healthOptions.ts
  src/test/unit/test/utils/validation.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-40

#49 coverage: update healthOptions unit test
  src/main/interfaces/FactRequest.ts
  src/main/modules/i18next/index.ts
  src/test/unit/test/utils/FactApi.ts
  src/test/unit/test/utils/healthOptions.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-49

#50 code refactor: undo the refactor for i18 that was part of pr-49 and i…
  src/main/modules/i18next/index.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-50

#57 Fact 72 add pa11y tests
  src/main/views/choose-action.njk
  src/main/views/search/option.njk
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-57

#69 Add appinsights
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app.ts
  src/main/modules/appinsights/index.ts
  src/main/modules/properties-volume/index.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-69

#66 Add proxy for API calls
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/modules/proxy/index.ts
  src/test/functional/features/api-proxy.feature
  src/test/functional/steps/api-proxy.ts
  src/test/functional/utlis/puppeteer.util.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-66

#73 Fact 53 locations details
  package.json
  src/main/views/court-details/in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-73

#75 fact-45-fix
  src/main/controllers/CourtDetailsController.ts
  src/main/controllers/search/LocationSearchController.ts
  src/main/controllers/search/SearchOptionController.ts
  src/main/controllers/search/SearchResultsController.ts
  src/main/routes.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/search/location.njk
  src/test/a11y/a11y.ts
  src/test/unit/test/controllers/CourtDetailsController.ts
  src/test/unit/test/controllers/search/LocationSearchController.ts
  src/test/unit/test/controllers/search/SearchOptionController.ts
  src/test/unit/test/controllers/search/SearchResultsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-75

#77 Revert i18n changes
  src/main/locales/cy/error.json
  src/main/locales/cy/home.json
  src/main/locales/cy/notFound.json
  src/main/locales/cy/template.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-77

#70 Update pally tests for search details page
  README.md
  package.json
  src/test/a11y/a11y.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-70

#78 Fact 102 access scheme
  api/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-78

#80 test ordering
  src/main/app.ts
  src/main/container.ts
  src/main/modules/awilix/index.ts
  src/test/unit/test/modules/i18next.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-80
