Repository hmcts/fact-frontend, pull requests merged in 2021-08, with the labels that each got.

#399 Removed hardcoding of breathing space
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/test/functional/features/court-details.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-399

#400 helm-chart-upgrade - Upgraded helm-chart version to 2.3.7
  charts/fact-frontend/Chart.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-400

#404 removing hardcoded index & logic fix for A to Z court search
  src/main/views/court-details/in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/A-Z-court-search.ts
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-404

#405 Remove logic to retrieve additional links based on sidebar location
  src/main/controllers/CourtDetailsController.ts
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/utils/CourtDetailsUtils.ts
  src/main/utils/SidebarLocation.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/controllers/CourtDetailsController.ts
  src/test/unit/test/utils/CourtDetailsUtils.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-405
