Repository hmcts/fact-frontend, pull requests merged in 2021-03, with the labels that each got.

#265 FACT-320 - Court name in page title and description
  src/main/controllers/CourtDetailsController.ts
  src/main/locales/cy/closed-court.json
  src/main/locales/cy/court-details.json
  src/main/locales/en/closed-court.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/closed-court.njk
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/template.njk
  src/test/functional/features/closed-court.feature
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-265

#267 FACT-357 - Service area listings in not-in-person-court P1
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/utils/CourtDetailsUtils.ts
  src/main/utils/validation.ts
  src/test/unit/test/utils/CourtDetailsUtils.ts
  src/test/unit/test/utils/validation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-267

#263 FACT-323: Not found page
  src/main/controllers/NotFoundPageController.ts
  src/main/locales/cy/notFound.json
  src/main/locales/en/notFound.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/not-found.njk
  src/test/functional/features/not-found-page.feature
  src/test/functional/steps/not-found-page.ts
  src/test/unit/test/controllers/NotFoundPageController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-263

#268 FACT-162 - Added fix for displaying of Enquiries when lang set to Welsh
  src/main/controllers/CourtDetailsController.ts
  src/main/utils/CourtDetailsUtils.ts
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-268

#272 FACT-361 - Implemented changes for go-live requirements
  src/main/locales/cy/choose-action.json
  src/main/locales/cy/choose-service.json
  src/main/locales/cy/court-details.json
  src/main/locales/cy/service.json
  src/main/locales/cy/unknownService.json
  src/main/locales/en/choose-action.json
  src/main/locales/en/choose-service.json
  src/main/locales/en/court-details.json
  src/main/locales/en/service.json
  src/main/views/choose-action.njk
  src/main/views/choose-service.njk
  src/main/views/court-details/in-person-court.njk
  src/main/views/search/location.njk
  src/main/views/service.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-272

#276 FACT-367 - Fix issues with tests using old, unsuitable prod data
  src/test/functional/features/court-details.feature
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-276

#274 FACT-333 - Added Google site verification metadata tag into page head
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-274

#278 FACT-357 - Updated P1 text on not-in-person courts to use area of law instead of service area
  src/main/controllers/CourtDetailsController.ts
  src/main/utils/CourtDetailsUtils.ts
  src/test/unit/test/utils/CourtDetailsUtils.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-278

#281 FACT-375 - Implemented healthcheck for mapit api service
  README.md
  config/default.yaml
  src/main/app.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-281

#289 remove proxy
  src/test/functional/puppeteer.config.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-289

#283 FACT-371 - Change heading for 'related content' for not in-person court page
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-283
