Repository hmcts/fact-frontend, pull requests merged in 2021-06, with the labels that each got.

#341 FACT-526 - Front end changes to find a court by prefix and list courts using A-Z
  src/main/controllers/search/CourtPrefixSearchController.ts
  src/main/interfaces/CourtResultsData.ts
  src/main/interfaces/CourtSearchData.ts
  src/main/interfaces/FactRequest.ts
  src/main/locales/cy/search/prefix-search.json
  src/main/locales/cy/unknownService.json
  src/main/locales/en/search/prefix-search.json
  src/main/locales/en/unknownService.json
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/utils/FactApi.ts
  src/main/views/search/prefix-search.njk
  src/main/views/unknown-service.njk
  src/test/functional/features/A-Z-court-search.feature
  src/test/functional/steps/A-Z-court-search.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/unit/test/controllers/search/CourtPrefixSearchController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-341

#348 CVE-2020-28469-Patch - Upgraded gulp-parent version
  package.json
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-348

#359 FACT-588 updating the frontend to fix vulnerabilities
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-359

#345 FACT-491 amending mobile issues, changing to use summary lists
  src/main/locales/cy/search/location.json
  src/main/locales/en/search/location.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/search/location.njk
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-345

#365 FACT-606 - Sanitised query string due to Fortify conerns.
  src/main/routes.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-365

#367 FACT-650 - Added sidebar link to HMCTS money claims for some not-in-p…
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-367

#368 FACT-650 - Moved new content from sidebar to inside email area
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-368

#369 Added CODEOWNERS file
  .github/CODEOWNERS
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-369

#370 FACT-673 - Created new temporary section in not-in-person court template
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-370
