Repository hmcts/fact-frontend, pull requests merged in 2021-07, with the labels that each got.

#385 FACT-673 CCMCC/OCMC updates
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/ApplicationUpdate.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/not-in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-385

#386 FACT-713 - Add new 'find out more' sidebar section
  src/main/interfaces/CourtDetailsData.ts
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-386

#390 FACT-769 - Display addition links for Financial Remedy to In-person and Not-in-person courts
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/utils/CourtDetailsUtils.ts
  src/main/utils/SidebarLocation.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
  src/test/resources/court-details-results.json
  src/test/resources/not-in-person-court-details-results.json
  src/test/unit/test/controllers/CourtDetailsController.ts
  src/test/unit/test/utils/CourtDetailsUtils.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-390
