Repository hmcts/fact-frontend, pull requests merged in 2021-12, with the labels that each got.

#449 addressing vulnerable dependencies identified by ithc testing
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-449

#452 fixing double forward slash image issue
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-452

#453 upping timeout to test accessibility failures
  jest.timeout.config.js
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-453
