Repository hmcts/fact-frontend, pull requests merged in 2021-04, with the labels that each got.

#290 FACT-361 - Corrected some welsh language translations
  src/main/locales/cy/court-details.json
  src/main/locales/cy/home.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/locales/cy/service.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-290

#295 FACT-389 - Updated cookie manager and cookie consent banner/form
  package.json
  src/main/assets/scss/main.scss
  src/main/index.js
  src/main/locales/cy/template.json
  src/main/locales/en/template.json
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  src/test/functional/steps/cookie-banner.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-295

#299 FACT-412 - Updated cookie manager version
  package.json
  src/main/index.js
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/js.njk
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-299

#302 FACT-366 - Added new postcode search feature
  src/main/controllers/service/ChooseServiceController.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/controllers/service/ServiceSearchResultsController.ts
  src/main/controllers/service/UnknownServiceController.ts
  src/main/interfaces/PostcodeResultsData.ts
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/postcode-search.json
  src/main/locales/cy/unknownService.json
  src/main/locales/en/postcode-results.json
  src/main/locales/en/postcode-search.json
  src/main/locales/en/unknownService.json
  src/main/routes.ts
  src/main/utils/FactApi.ts
  src/main/views/postcode-results.njk
  src/main/views/postcode-search.njk
  src/main/views/unknown-service.njk
  src/test/functional/features/postcode-search.feature
  src/test/unit/test/controllers/UnknownServiceController.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-302

#303 FACT-366 Default UnknownService Behaviour + Func tests for each journey
  src/main/controllers/service/ChooseServiceController.ts
  src/main/controllers/service/UnknownServiceController.ts
  src/main/locales/cy/unknownService.json
  src/main/locales/en/unknownService.json
  src/main/views/unknown-service.njk
  src/test/functional/features/postcode-results.feature
  src/test/functional/steps/postcode-search.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-303

#296 FACT-374 - Added in Dynatrace RUM and cookie consent
  src/main/index.js
  src/main/locales/cy/cookies.json
  src/main/locales/cy/template.json
  src/main/locales/en/cookies.json
  src/main/locales/en/template.json
  src/main/views/cookies.njk
  src/main/views/webpack/js.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-296

#312 FACT-374 - Dynatrace Cookie Banner revision
  src/main/locales/cy/cookies.json
  src/main/locales/cy/template.json
  src/main/locales/en/cookies.json
  src/main/locales/en/template.json
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-312

#317 FACT-374 - Updated cookie preference page APM description
  src/main/locales/cy/cookies.json
  src/main/locales/en/cookies.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-317

#318 ga-patch - Fix for using GTAG (GA4) implementation for disabling GA rather than UA implementation.
  src/main/index.js
  src/main/views/template.njk
  src/main/views/webpack/js.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-318

#320 FACT-411 - Added in Breathing Space content
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-320
