Repository hmcts/fact-frontend, pull requests merged in 2021-02, with the labels that each got.

#239 FACT-337 add error messages to GA datalayer
  src/main/views/macros/error-summary.njk
  src/test/functional/features/datalayer.feature
  src/test/functional/steps/datalayer.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-239

#240 Fact 338 datalayer language
  src/main/views/template.njk
  src/test/functional/features/datalayer.feature
  src/test/functional/steps/datalayer.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-240

#243 Fact 339 datalayer user selection
  src/main/controllers/service/ChooseServiceController.ts
  src/main/views/choose-action.njk
  src/main/views/choose-service.njk
  src/main/views/search/option.njk
  src/main/views/service.njk
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-243

#241 Fact 319 inperson court metadata
  charts/fact-frontend/Chart.yaml
  charts/fact-frontend/values.yaml
  config/custom-environment-variables.yaml
  src/main/controllers/CourtDetailsController.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/macros/location-seo-metadata.njk
  src/test/functional/features/court-seo-metadata.feature
  src/test/functional/steps/court-seo-metadata.ts
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-241

#247 FACT-349: Fix bug in postcode validation
  src/main/utils/validation.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-247

#249 Fact 317
  src/main/locales/cy/postcode-search.json
  src/main/locales/en/postcode-search.json
  src/main/views/template.njk
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-249

#250 Fact 308
  src/main/locales/cy/search/option.json
  src/main/locales/en/search/option.json
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-250

#251 FACT-309 Add seo metadata description for search by name page
  src/main/locales/cy/search/location.json
  src/main/locales/cy/search/option.json
  src/main/locales/en/search/location.json
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-251

#252 FACT-310 Add seo metadata description for choose action page
  src/main/locales/cy/choose-action.json
  src/main/locales/en/choose-action.json
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/help-and-navigation.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/features/no-name.feature
  src/test/functional/features/postcode-results.feature
  src/test/functional/features/postcode-search.feature
  src/test/functional/features/services.feature
  src/test/functional/features/view-immigration-result.feature
  src/test/functional/features/view-money-claims-result.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-252

#253 FACT-311 Add metadata description
  src/main/locales/cy/choose-service.json
  src/main/locales/en/choose-service.json
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/help-and-navigation.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/features/services.feature
  src/test/functional/features/view-immigration-result.feature
  src/test/functional/features/view-money-claims-result.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-253

#254 FACT-318 Add seo metadata description to search results page
  src/main/locales/cy/postcode-results.json
  src/main/locales/cy/service-results.json
  src/main/locales/en/postcode-results.json
  src/main/locales/en/service-results.json
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/view-immigration-result.feature
  src/test/functional/features/view-money-claims-result.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-254

#255 FACT-322 Add seo metadata description to service not found page
  src/main/locales/cy/unknownService.json
  src/main/locales/en/unknownService.json
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/unknown-service.feature
  src/test/functional/steps/description-seo-metadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-255

#256 FACT-312, FACT-313, FACT-314, FACT-315, FACT-316, FACT-352 and FACT-3…
  src/main/controllers/service/ChooseServiceAreaController.ts
  src/main/locales/cy/service.json
  src/main/locales/en/service.json
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/steps/description-seo-metadata.ts
  src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-256

#257 FACT 347 - Add not-in-person court metadata
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/CourtDetailsData.ts
  src/main/interfaces/seo/PlaceSEOMetadata.ts
  src/main/utils/SEOMetadata.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/macros/location-seo-metadata.njk
  src/test/functional/features/court-seo-metadata.feature
  src/test/functional/steps/court-seo-metadata.ts
  src/test/unit/test/controllers/CourtDetailsController.ts
  src/test/unit/test/utils/SEOMetadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-257

#259 FACT-fixSEOImage - potentional fix for not-in-person courts showing a…
  src/main/utils/SEOMetadata.ts
  src/test/unit/test/utils/SEOMetadata.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-259

#262 FACT-350: Iterate over 'enquiries' emails and add description.
  src/main/controllers/CourtDetailsController.ts
  src/main/interfaces/Enquiries.ts
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-262

#260 Fact 320
  src/main/controllers/CourtDetailsController.ts
  src/main/locales/cy/accessibility-statement.json
  src/main/locales/cy/closed-court.json
  src/main/locales/cy/cookies.json
  src/main/locales/cy/court-details.json
  src/main/locales/en/accessibility-statement.json
  src/main/locales/en/choose-action.json
  src/main/locales/en/choose-service.json
  src/main/locales/en/closed-court.json
  src/main/locales/en/cookies.json
  src/main/locales/en/court-details.json
  src/main/locales/en/home.json
  src/main/locales/en/postcode-results.json
  src/main/locales/en/postcode-search.json
  src/main/locales/en/search/location.json
  src/main/locales/en/search/option.json
  src/main/locales/en/service-results.json
  src/main/locales/en/service.json
  src/main/locales/en/unknownService.json
  src/main/routes.ts
  src/test/functional/features/childcare-and-parenting-service-area.feature
  src/test/functional/features/closed-court.feature
  src/test/functional/features/cookie-banner.feature
  src/test/functional/features/crime-service-area.feature
  src/test/functional/features/description-seo-metadata.feature
  src/test/functional/features/family-service-area.feature
  src/test/functional/features/harm-and-abuse-service-area.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/money-service-area.feature
  src/test/functional/features/postcode-results.feature
  src/test/functional/features/postcode-search.feature
  src/test/functional/steps/description-seo-metadata.ts
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-260

#264 FACT-356: Welsh translation for cookies page.
  src/main/locales/cy/cookies.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-264
