Repository hmcts/fact-frontend, pull requests merged in 2022-08, with the labels that each got.

#610 FACT-1225 added safe to allow links to show properly
  src/main/views/court-details/in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-610

#578 Fact 500
  src/main/controllers/ProxyController.ts
  src/main/controllers/service/ServiceAreaRedirect.ts
  src/main/controllers/service/ServicePostcodeResultsController.ts
  src/main/controllers/service/ServicePostcodeSearchController.ts
  src/main/routes.ts
  src/main/utils/FactApi.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/postcode-results.feature
  src/test/functional/steps/description-seo-metadata.ts
  src/test/functional/steps/postcode-results.ts
  src/test/unit/test/controllers/ProxyControllerTest.ts
  src/test/unit/test/controllers/service/ServiceAreaRedirect.ts
  src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
  src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-578

#623 updating in person/not in person courts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-623

#624 updating labels
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-624

#632 Add backstage configuration file
  catalog-info.yaml
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-632
