Repository hmcts/fact-frontend, pull requests merged in 2022-09, with the labels that each got.

#641 updating frontend
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-641

#646 adding fortify to nightly
  Jenkinsfile_nightly
  java/.gitignore
  java/build.gradle
  java/config/fortify-client.properties
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
  java/gradlew
  java/gradlew.bat
  java/settings.gradle
  package.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-646

#650 removing unneeded key
  src/main/resources/localhost-ssl/README.md
  src/main/resources/localhost-ssl/localhost.crt
  src/main/resources/localhost-ssl/localhost.key
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-650

#651 FACT-1232 accessibility changes for EN and CY
  src/main/locales/cy/accessibility-statement.json
  src/main/locales/en/accessibility-statement.json
  src/main/views/accessibility-statement.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-651

#653 FACT-1232 added missing characters
  src/main/locales/cy/accessibility-statement.json
  src/main/locales/en/accessibility-statement.json
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-653
