Repository hmcts/fact-frontend, pull requests merged in 2022-12, with the labels that each got.

#690 fixed warnings
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-690

#697 added renovate.json file in base directory
  renovate.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-697

#689 FACT-1258 changes to show new court codes for tribunal and family
  src/main/interfaces/CourtDetailsData.ts
  src/main/locales/cy/court-details.json
  src/main/locales/en/court-details.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/controllers/CourtDetailsController.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-689

#694 FACT-1187 fixed issue with not in person court page
  src/main/views/court-details/not-in-person-court.njk
Labels: bug, ns:fact, prd:fact, rel:fact-frontend-pr-694

#701 update css file name
  package.json
  src/main/views/webpack/css.njk
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-701

#702 add renovate.json
  .github/dependabot.yml
  .github/renovate.json
  renovate.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-702

#704 renovatebot config error fix
  .github/renovate.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-704
