Repository hmcts/fact-frontend, pull requests merged in 2022-05, with the labels that each got.

#543 adding additional court addresses and description field
  package.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/resources/court-details-results.json
  src/test/resources/not-in-person-court-details-results.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-543

#541 Upgrade to @hmcts/cookie-manager v1.0.0
  package.json
  src/main/index.js
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/js.njk
  src/test/functional/steps/cookie-banner.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-541

#564 Fact 1071 a11y test
  src/test/a11y/a11y.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-564
