Repository hmcts/fact-frontend, pull requests merged in 2022-04, with the labels that each got.

#533 adding _oauth2_proxy to cookie manifest
  package.json
  src/main/index.js
  src/main/views/webpack/js.njk
  src/test/functional/features/court-details.feature
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-533

#537 fix vulnerabilities
  package.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-537

#532 Fact 1155
  src/main/controllers/ProxyController.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/test/functional/features/api-proxy.feature
  src/test/functional/steps/api-proxy.ts
  src/test/unit/test/controllers/ProxyControllerTest.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-532
