Repository hmcts/fact-frontend, pull requests merged in 2024-12, with the labels that each got.

#808 FACT-2096 - Prefix Search Fix
  .pnp.cjs
  package.json
  src/main/controllers/search/CourtPrefixSearchController.ts
  src/test/unit/test/controllers/search/CourtPrefixSearchController.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-808

#810 Fix for path-to-regexp vulnerability
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-810

#811 FACT-2115 - CVEs
  .pnp.cjs
  .yarn/cache/@jest-schemas-npm-28.1.3-231835b296-3cf1d4b66c.zip
  .yarn/cache/@jest-types-npm-28.1.3-422ad1bd71-1e258d9c06.zip
  .yarn/cache/@playwright-test-npm-1.48.2-07215b842c-926e9411c8.zip
  .yarn/cache/@sinclair-typebox-npm-0.24.51-cdde4a266f-fd0d855e74.zip
  .yarn/cache/@types-cookie-parser-npm-1.4.7-b74a485836-7b87c59420.zip
  .yarn/cache/@types-node-npm-18.19.64-2bf88f0be4-e7680215b0.zip
  .yarn/cache/@webassemblyjs-ast-npm-1.12.1-3ff9ea1c0e-31bcc64147.zip
  .yarn/cache/@webassemblyjs-floating-point-hex-parser-npm-1.11.6-3a9928fc76-29b0875884.zip
  .yarn/cache/@webassemblyjs-helper-api-error-npm-1.11.6-75f6275ff4-e8563df851.zip
  .yarn/cache/@webassemblyjs-helper-buffer-npm-1.12.1-d025434a45-c3ffb72302.zip
  .yarn/cache/@webassemblyjs-helper-numbers-npm-1.11.6-819ddab1da-f4b562fa21.zip
  .yarn/cache/@webassemblyjs-helper-wasm-bytecode-npm-1.11.6-3bc23747de-3535ef4f1f.zip
  .yarn/cache/@webassemblyjs-helper-wasm-section-npm-1.12.1-cd0e2f1eab-c19810cdd2.zip
  .yarn/cache/@webassemblyjs-ieee754-npm-1.11.6-95c92f446a-13574b8e41.zip
  .yarn/cache/@webassemblyjs-leb128-npm-1.11.6-697d62da2e-7ea942dc97.zip
  .yarn/cache/@webassemblyjs-utf8-npm-1.11.6-102c4e5d68-807fe5b5ce.zip
  .yarn/cache/@webassemblyjs-wasm-edit-npm-1.12.1-727bec592a-ae23642303.zip
  .yarn/cache/@webassemblyjs-wasm-gen-npm-1.12.1-bbe22ad265-5787626bb7.zip
  .yarn/cache/@webassemblyjs-wasm-opt-npm-1.12.1-450c932de6-0e8fa8a064.zip
  .yarn/cache/@webassemblyjs-wasm-parser-npm-1.12.1-54a7a19806-176015de35.zip
  .yarn/cache/@webassemblyjs-wast-printer-npm-1.12.1-e75655c7ff-2974b5dda8.zip
  .yarn/cache/express-npm-4.21.0-377d90d8f4-1c5212993f.zip
  .yarn/cache/i18next-http-middleware-npm-3.6.0-cdb37611aa-d11e0ca42a.zip
  .yarn/cache/immutable-npm-4.3.4-2f54cf641b-de3edd964c.zip
  .yarn/cache/jest-util-npm-28.1.3-9ae2283a08-fd6459742c.zip
  .yarn/cache/nock-npm-13.5.5-ccb57f0a2f-91947b6839.zip
  .yarn/cache/path-to-regexp-npm-0.1.10-63516149e0-ab7a3b7a0b.zip
  .yarn/cache/playwright-core-npm-1.30.0-ed7c04af76-4c5693f272.zip
  .yarn/cache/playwright-core-npm-1.48.2-f1270e8a40-a73ecea379.zip
  .yarn/cache/playwright-npm-1.30.0-54cd38918f-1987446ed0.zip
  .yarn/cache/playwright-npm-1.48.2-7628504eaa-69ffb28b5a.zip
  .yarn/cache/sass-loader-npm-16.0.3-70aa568612-888b2fbe4e.zip
  .yarn/cache/sass-npm-1.80.6-30d57f2c14-1a81e0fe09.zip
  .yarn/cache/ts-jest-npm-28.0.8-eeca582fd6-c72e929270.zip
  .yarn/cache/webpack-npm-5.96.1-1a1f8d3a52-ec3662f648.zip
  .yarn/install-state.gz
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-811

#812 Quick fix on nightly/master
  Jenkinsfile_nightly
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-812

#809 FACT-2045 remove no-store from cache-control header
  src/main/app.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-809
