Repository hmcts/fact-frontend, pull requests merged in 2024-09, with the labels that each got.

#789 FACT-1947 update dependancies
  .pnp.cjs
  .yarn/cache/micromatch-npm-4.0.5-cfab5d7669-02a17b671c.zip
  .yarn/install-state.gz
  README.md
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-789

#794 FACT-1947 fixing dependancies
  .pnp.cjs
  .yarn/cache/@hmcts-info-provider-npm-1.1.0-ff33fd10d2-e1ddca0e05.zip
  .yarn/cache/axios-npm-1.6.7-d7b9974d1b-87d4d42992.zip
  .yarn/cache/body-parser-npm-1.20.2-44738662cf-14d37ec638.zip
  .yarn/cache/express-npm-4.19.2-f81334a22a-212dbd6c2c.zip
  .yarn/cache/finalhandler-npm-1.2.0-593d001463-92effbfd32.zip
  .yarn/cache/ip-npm-2.0.1-ee48691f03-d765c9fd21.zip
  .yarn/cache/merge-descriptors-npm-1.0.1-615287aaa8-5abc259d2a.zip
  .yarn/cache/path-to-regexp-npm-0.1.7-2605347373-69a14ea24d.zip
  .yarn/cache/send-npm-0.18.0-faadf6353f-74fc07ebb5.zip
  .yarn/cache/serve-static-npm-1.15.0-86c81879f5-af57fc13be.zip
  .yarn/install-state.gz
  README.md
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-794

#795 Remove old bot cleanup
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-795
