Repository hmcts/fact-frontend, pull requests merged in 2024-07, with the labels that each got.

#777 Test2
  .gitignore
  .yarn/install-state.gz
  src/test/functional/steps/no-name.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-777

#779 fact frontend fix func tests
  src/test/config.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-779

#767 FACT-1658 court history names frontend changes
  .yarn/install-state.gz
  src/main/controllers/search/SearchResultsController.ts
  src/main/interfaces/SearchResultsData.ts
  src/main/locales/cy/search/location.json
  src/main/locales/en/search/location.json
  src/main/utils/FactApi.ts
  src/main/views/search/location.njk
  src/test/unit/test/controllers/search/SearchResultsController.ts
  src/test/unit/test/utils/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-767

#780 FACT-1881 changed docker db from from to use imported
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  docker/database/Dockerfile
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-780

#781 FACT-1881 remove bit not needed
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-781
