Repository hmcts/fact-frontend, pull requests merged in 2024-03, with the labels that each got.

#756 Accessibility WCAG FACT 3.1.1: Language of Page (Level A)
  src/main/locales/cy/cookies.json
  src/main/locales/en/cookies.json
  src/main/views/cookies.njk
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-756

#755 FACT-1599 changed frontend to add new tab changes
  .pnp.cjs
  .yarn/cache/axios-npm-0.26.1-a6641ce4e3-d9eb58ff4b.zip
  .yarn/cache/axios-npm-1.3.3-27e5c9cf4a-b734a4bc34.zip
  .yarn/cache/ip-npm-2.0.0-204facb3cc-cfcfac6b87.zip
  .yarn/cache/playwright-core-npm-1.30.0-ed7c04af76-4c5693f272.zip
  .yarn/cache/playwright-npm-1.30.0-54cd38918f-1987446ed0.zip
  .yarn/install-state.gz
  package.json
  src/main/locales/cy/home.json
  src/main/locales/en/home.json
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/main/views/home.njk
  src/test/functional/features/court-details.feature
  src/test/functional/steps/court-details.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-755

#758 follow redirects updated and known issues cleared
  .pnp.cjs
  .yarn/cache/follow-redirects-npm-1.15.5-9d14db76ca-5ca49b5ce6.zip
  .yarn/install-state.gz
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-758
