Repository hmcts/fact-frontend, pull requests merged in 2025-03, with the labels that each got.

#815 FACT-2206 - Append warning when link opens in new window
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/court-details/in-person-court.njk
  src/main/views/court-details/not-in-person-court.njk
  src/test/unit/test/modules/nunjucks/njkFilters.ts
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-815

#816 NO-TICKET - vulnerability fix
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-816

#820 CVE fix - @babel/runtime
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.21.5-7d058028a3-7cd4f9be85.zip
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-frontend-pr-820
